### ISSUE TITLE
Script can't find ffmpeg

### ISSUE THREAD

**Issue by hellocatfood** [Akascape/FF-Dissolve-Glitch#1]
Thanks for making this tool!

I'm trying to use the script but when I run `python3.9 FF\ Dissolve\ Glitch.py` a window appears telling me to download ffmpeg.

![Screenshot from 2022-02-08 11-35-46](https://user-images.githubusercontent.com/151947/152979528-fcbe15ac-d009-4817-ad04-a7dd8c8b1197.png)

I've checked and I definitely have ffmpeg installed (7:4.4-6ubuntu5) so it seems like it's not correctly detecting it on Linux. Any chance of making it compatible with Linux. For reference I'm using Ubuntu 21.10 with python 3.9.9.

**Comment by Akascape** [comment]
Ok, please remove line 17 from the script and then try to run it again. The error message will not pop up again.
Please let me know if it is working properly or not.

**Comment by Akascape** [comment]
Ok, please remove line 17 from the script and then try to run it again. The error message will not pop up.
Please let me know if it is working properly or not.

**Comment by hellocatfood** [comment]
that didn't solve it unfortunately. Removing line 17 and running it again gave this error:
```
Traceback (most recent call last):
  File "/home/User/FF-Dissolve-Glitch/Python Version/FF Dissolve Glitch.py", line 102, in <module>
    root.wm_iconbitmap(path)
  File "/usr/lib/python3.9/tkinter/__init__.py", line 2080, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, bitmap)
_tkinter.TclError: bitmap "/home/User/FF-Dissolve-Glitch/Python Version/Programicon.ico" not defined
```

**Comment by Akascape** [comment]
This error is due to the icon file not available. Please download the Programicon.ico file from the repository and save it in the same directory.

**Comment by Akascape** [comment]
For you, I made another simplified script and tested it inside Ubuntu and it is working. Check here: [Python Version/FF Dissolve Glitch simplified.py](https://github.com/Akascape/FF-Dissolve-Glitch/blob/5b46f7b911ca96ef01ee17fe2f35598767d1130f/Python%20Version/FF%20Dissolve%20Glitch%20simplified.py)

**Comment by Akascape** [comment]
For you, I made another simplified script and tested it inside Ubuntu and it was working. Check here to see: [Python Version/FF Dissolve Glitch simplified.py](https://github.com/Akascape/FF-Dissolve-Glitch/blob/5b46f7b911ca96ef01ee17fe2f35598767d1130f/Python%20Version/FF%20Dissolve%20Glitch%20simplified.py)

**Comment by hellocatfood** [comment]
Thanks for this! Just wondering though, isn't there a way to create a version that can find ffmpeg regardless of OS?

**Comment by Akascape** [comment]
The issue is with the subprocess command. I forgot to add the shell=True line due to which it was unable to open the terminal.
In windows we don't need to specify the shell.
