### ISSUE TITLE
FF_dissolve_glitch_simplified.py window really small/squashed

### ISSUE THREAD

**Issue by hellocatfood** [Akascape/FF-Dissolve-Glitch#2]
I'm trying to use `FF_dissolve_glitch_simplified.py` on Ubuntu 22.04 with python 3.10 and the window size is really small

![Screenshot from 2022-06-11 20-27-17](https://user-images.githubusercontent.com/151947/173202170-3fc10393-314e-42ee-90e5-712fefdb2ae1.png)

It can't be resized either (no resize handles appear and the resize option is greyed out).

**Comment by Akascape** [comment]
@hellocatfood OK, I built the linux version again in Ubuntu 22 this time, check the linux folder inside python version. Now it can find ffmpeg automatically,
![Screenshot 2022-06-12 122154](https://user-images.githubusercontent.com/89206401/173221737-a14de1a4-bd10-4a79-bafd-09153e3087b3.png)

I have tested it and it is working properly. I used Ubuntu 22.04, python 3.10. 

If you are still getting a messed up GUI, then change your **font size** to default in Ubuntu. 
Or you can also change font in the program in the line #15.

**Comment by hellocatfood** [comment]
I just tried this again and getting the same result. I did some digging and it seems the script window sizing is reacting the window scaling. 

I have a HiDPI screen (3840x2400) and have scaling set to 200%
![Screenshot from 2022-06-13 22-17-48](https://user-images.githubusercontent.com/151947/173447494-78550a8e-c596-4624-8ef3-2a89a12207a3.png)

At this setting it is the only window where all of the UI elements appear squashed

**Comment by Akascape** [comment]
Hi @hellocatfood, 
I just changed the whole UI of ff-dissolve glitch to a modern look. Now it looks like this:
![](https://user-images.githubusercontent.com/89206401/206907828-3775c4b6-ab6f-4168-83d9-d2bfb1dbea24.jpg)
Hope you will like this :)

**Comment by hellocatfood** [comment]
Looks great, though I still can't get it to work :-( I'll report a separate bug
